spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.100.164.22:3306/mysite?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: chen@1997


mybatis-plus:    # 使用mybatis 打印日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl